# Generated by Django 5.1.2 on 2024-10-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='counter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='password',
            name='time_called',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
